user:
  api_key: jfCGTjZcCIuPDUbdDt
  api_secret: IHz2iqBanafGGuesd0w4QKjrQyUb2NDgQ0q1
settings:
  def_coin: BTC
  plot_display: Price
  balance_plot_period: 10 min
  PMA:
  - 0
  - 0
  - 0
  - 0
  - 0
  BMA:
  - 0
  - 0
  testing: true
  trade_amount: 1
  loss_amount: 5
  loss_period: 10
  btc_model:
    location: null
    seq: null
    batch: null
    future: null
    moving_avg: null
    e_moving_avg: null
    drop: null
  eth_model:
    location: null
    seq: null
    batch: null
    future: null
    moving_avg: null
    e_moving_avg: null
    drop: null
  xrp_model:
    location: null
    seq: null
    batch: null
    future: null
    moving_avg: null
    e_moving_avg: null
    drop: null
  eos_model:
    location: null
    seq: null
    batch: null
    future: null
    moving_avg: null
    e_moving_avg: null
    drop: null
  model_arguments:
    target: BTC
    future: 1
    size: 1000
    period: 1
    epochs: 10
    seq: 128
    batch: 64
    ma:
    - 5
    - 10
    ema:
    - 4
    - 8
  model_blueprint:
  - &id001
    layer: Dense
    n: 16
    drop: 0.0
  - *id001
  - *id001
stats:
  total_profit: 4.573251474999999
  last_cap_bal: 4.573251474999999
  last_trade_profit: 0
  total_prediction: 0
  correct_prediction: 0
