user:
  api_key: 
  api_secret: 
settings:
  def_coin: BTC
  leverage: 1
  plot_display: Both
  balance_plot_period: 10 min
  PMA:
  - 0
  - 0
  - 0
  - 0
  - 1
  BMA:
  - 0
  - 0
  - 0
  - 0
  - 1
  testing: true
  trade_amount: 1
  loss_amount: 5
  loss_period: 10
  btc_model:
    location: null
    seq: null
    batch: null
    future: null
    moving_avg: null
    e_moving_avg: null
    drop: null
    period: null
    layers: null
  eth_model:
    location: null
    seq: null
    batch: null
    future: null
    moving_avg: null
    e_moving_avg: null
    drop: null
    period: null
    layers: null
  xrp_model:
    location: null
    seq: null
    batch: null
    future: null
    moving_avg: null
    e_moving_avg: null
    drop: null
    period: null
    layers: null
  eos_model:
    location: null
    seq: null
    batch: null
    future: null
    moving_avg: null
    e_moving_avg: null
    drop: null
    period: null
    layers: null
  default_model_arguments:
    target: ETH
    future: 1
    size: 1000
    period: 30
    epochs: 20
    seq: 128
    batch: 64
    ma:
    - 15
    ema:
    - 10
  model_blueprint:
  - layer: LSTM
    n: 25
    drop: 0.2
  - layer: Dense
    n: 15
    drop: 0.0
stats:
  total_profit: -0.10981070199999987
  last_cap_bal: 2.9278550095
  total_prediction: 0
  correct_prediction: 0
